[package]
name = "wiki-db"
version = "0.1.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
edition = "2018"

[dependencies]
rocksdb="*"
tantivy="*"
serde="*"
serde_derive="*"
serde_yaml="*"
serde_json="*"
sha2="*"
wiki-log = { path = "../wiki-log" }
failure="^0.1.3"
