[package]
name = "wiki-vm"
version = "0.1.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
edition = "2018"
crate-type = ["dylib"]

[dependencies]
mozjs="*"
libc = "0.2"
wiki-log={ path = "../wiki-log" }
