[package]
name = "wiki-log"
version = "0.1.0"
authors = ["Stanislav Panferov <fnight.m@gmail.com>"]
edition = "2018"

[dependencies]
slog="*"
slog-json="*"
slog-term="*"
slog-async="*"
slog-scope="*"

